### PR TITLE
Add MailMessage stub to work well with Mailable

### PR DESCRIPTION
**Pull request by pionl**
👋

- [x] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

This changes allows using MailMessage with mailable `$mailable->markdown($mailMessage->markdown, $mailMessage->data())`

```
Parameter #1 $view of method Illuminate\Mail\Mailable::markdown() expects view-string, string|null given.  
```

```php
class Mail extends Mailable
{
    public function __construct(
        private string $test,
    ) {
    }

    public function build(): self
    {
        $message = new MailMessage();
        $message->line('Test line ' . $this->test);

        return $this
            ->subject('Test ' . $this->test)
            ->markdown($message->markdown, $message->data()); 👈🏻 
    }
}
```

### CODE REVIEW

**Comment by pionl** [comment]
Tests passes except this one `tests/Type/data/request-object.php`:

```
1) Type\GeneralTypeTest::testFileAsserts with data set "/Users/pion/Work/OpenSource/larastan/tests/Type/data/request-object.php:18" ('type', '/Users/pion/Work/OpenSource/l...ct.php', PHPStan\Type\Constant\ConstantStringType Object (...), PHPStan\Type\UnionType Object (...), 18)
Expected type Illuminate\Foundation\Auth\User|null, got type App\User|null in /Users/pion/Work/OpenSource/larastan/tests/Type/data/request-object.php on line 18.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Illuminate\Foundation\Auth\User|null'
+'App\User|null'
```

If I correctly understand `LoadsAuthModel` class should typehint correct class used in auth config but the test is not updated?

**Comment by szepeviktor** [comment]
Let's see that failing test in CI!

**Comment by mad-briller** [comment]
i've been experiencing that test failure too @pionl when running them locally, but they don't seem to fail in the github actions,
it fails on the latest master straight after a clone and `composer update`

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/larastan/blob/7071c693df1123fb1e7281333cebf5eee05c65aa/tests/Type/data/request-object.php#L18

You have to be a Chinese doctor to handle the healthy :)

**Comment by pionl** [comment]
Is there anything that is blocking this PR? :) Should I do something? Thank you

**Comment by canvural** [comment]
Hi,

Thank you for the PR and I'm sorry for getting back too late!

I do not really understand what this PR is adding. What is the current error you get without these changes?

**Comment by pionl** [comment]
Last version i think we used:

PHPStan Version: 1.8.2
LaraStan: 2.1.12 

Output if i hide my own stub:

```
 ------ ----------------------------------------------------------------------------------------------------------- 
  Line   app/CommunityInvite/Mails/InviteMail.php                                                                   
 ------ ----------------------------------------------------------------------------------------------------------- 
  41     Parameter #1 $view of method Illuminate\Mail\Mailable::markdown() expects view-string, string|null given.  
 ------ ----------------------------------------------------------------------------------------------------------- 
```

After updating to latest versions same result.

**Comment by nunomaduro** [comment]
We've closed the `master` branch. Please open a new pull request and target the `2.x` branch if you wish to re-open this pull request.

**Pull request closed without merging**
