### PR TITLE
feat: Auth::user() returns all auth models when no parameter specified

### LINKED ISSUE #1230: `FormRequest::user()`always returns the model of default guard
- Larastan Version: 2.1.4
- `--level` used: 9
- Pull request with failing test:

### Description

It seems like `FormRequest::user()` method is stated to return the model of default guard, even though multiple guards defined in the `config/auth.php`.

Providing the name of the (non-default) guard with the method argument won't help; the method is still predicted to return the default.

### Laravel code where the issue was found

Let's say the default guard is `default_user` and model is `\App\Models\DefaultUser`.

```php
class ExampleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() instanceof \App\Models\AnotherUser;
        // or return $this->user('another_user') instanceof \App\Models\AnotherUser;
    }
}
```

It gives me the following error:
```
Instanceof between App\Models\DefaultUser|null and App\Models\AnotherUser will always evaluate to false.
```

### PR DESCRIPTION
**Pull request by mirucon**
- [x] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves #1230

**Changes**

Currently when no $guard parameter is passed to `Auth::user()` method, it always returns the model of *default* guard.
However this behaviour doesn't match how the method actually works as it might return non-default models as well.
This PR corrected the `Auth::user()` method to return all possible auth models.

p.s. I had no idea what `src/Methods/Pipes/Auths.php` is for, so please kindly let me know how I should handle this one.

**Breaking changes**

Yes

### CODE REVIEW

**Comment by szepeviktor** [comment]
Hello @mirucon!
Thank you for your contribution.

I think `empty()` is not out friend, it is way too complex.

**Comment by mirucon** [comment]
Hi @szepeviktor thanks for your response!
I replaced `empty()` with `count()` method, I hope this is what you mean.

**Comment by canvural** [comment]
Hi,

Can you explain how `Auth::user()` would return non-default user model? [Looks like](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/AuthManager.php#L64) it chooses the default guard if you don't pass any guard name.

**Comment by calebdw** [comment]
@canvural, I'm running into this issue as well.

The default guard is overridden by Laravel when setting the current guard to use.

https://github.com/laravel/framework/blob/0c574d42e9c7d82a0bd304a5cb2ce031a914bfa6/src/Illuminate/Auth/AuthManager.php#L201-L214

I have a project with several guards and use the `shouldUse` method in a middleware depending on the route. But of course Larastan doesn't know this.

Depending on the location in the code, `Auth::user()` returns a different auth model.

**Comment by calebdw** [comment]
@nunomaduro, can you  please reconsider this? This functionality is exactly how the `Auth::user()` method should work because Laravel overwrites the default guard at runtime. Calling `Auth::user()` in different locations in my codebase results in different auth models being returned.

**Comment by nunomaduro** [comment]
We've closed the `master` branch. Please open a new PR and target 2.x branch if you wish to re-open this PR.

**Pull request closed without merging**
