### PR TITLE
Move tests to PSR-4 structure

### PR DESCRIPTION
**Pull request by szepeviktor**
- [x] Added or updated tests
- [ ] Documented user facing changes

**Changes**

**Breaking changes**

### CODE REVIEW

**Comment by canvural** [comment]
Hi,

Are you gonna fix the issues with tests?

**Comment by szepeviktor** [comment]
Trying now ...

**Comment by szepeviktor** [comment]
I think the only remaining problem that `class Foo` is defined in several files.
PHPUnit does not think in PSR-4!

**Comment by nunomaduro** [comment]
We've closed the `master` branch. Please open a new pull request and target the `2.x` branch if you wish to re-open this pull request.

**Pull request closed without merging**
